// figma-output/src/app/components/MatchCard.tsx
import { Clock, Trophy, Zap, Loader2, CheckCircle2, AlertCircle } from 'lucide-react';
import { useState } from 'react';

interface MatchCardProps {
  teamA: string;
  teamB: string;
  flagA: string;
  flagB: string;
  date: string;
  time: string;
  reward: number;
  theme: 'orange' | 'green';
  prediction?: 'A' | 'draw' | 'B';
  onPredict?: (prediction: 'A' | 'draw' | 'B') => void;
  hasStarted?: boolean;
}

export function MatchCard({
  teamA,
  teamB,
  flagA,
  flagB,
  date,
  time,
  reward,
  theme,
  prediction,
  onPredict,
  hasStarted = false,
}: MatchCardProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);

  const themeGradient = theme === 'orange'
    ? 'bg-gradient-to-r from-[#FF6600] to-[#FF4500]'
    : 'bg-gradient-to-r from-[#28A745] to-[#218838]';
  const themeBorder = theme === 'orange' ? 'border-[#FF6600]' : 'border-[#28A745]';
  const themeBg = theme === 'orange' ? 'bg-[#FF6600]' : 'bg-[#28A745]';

  const handleVote = async (vote: 'A' | 'draw' | 'B') => {
    if (hasStarted || isLoading) return;

    setIsLoading(true);

    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 800));

    onPredict?.(vote);
    setIsLoading(false);
    setShowSuccess(true);

    setTimeout(() => setShowSuccess(false), 3000);
  };

  return (
    <div className={`relative bg-white rounded-xl shadow-md border border-gray-100 p-5 hover:shadow-xl hover:border-gray-200 transition-all ${hasStarted ? 'opacity-60' : ''}`}>
      {/* Success Notification */}
      {showSuccess && (
        <div className="absolute top-4 left-1/2 transform -translate-x-1/2 z-20 bg-green-500 text-white px-4 py-2 rounded-lg shadow-lg flex items-center gap-2 animate-in fade-in slide-in-from-top-2">
          <CheckCircle2 className="w-4 h-4" />
          <span className="text-xs font-medium">رای شما ثبت شد</span>
        </div>
      )}

      {/* Header */}
      <div className={`flex items-center justify-between mb-4 ${hasStarted ? 'blur-[0.5px]' : ''}`}>
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <Clock className="w-4 h-4" />
          <span>{date} • {time}</span>
        </div>
        <div className={`${themeGradient} text-white px-3 py-1.5 rounded-full text-xs font-bold flex items-center gap-1.5 shadow-lg`}>
          <Trophy className="w-3.5 h-3.5" />
          <span>{reward.toLocaleString('fa-IR')} تومان</span>
        </div>
      </div>

      {/* Teams */}
      <div className={`flex items-center justify-between mb-6 ${hasStarted ? 'blur-[0.5px]' : ''}`}>
        <div className="flex flex-col items-center gap-2 flex-1">
          <div className="text-4xl">{flagA}</div>
          <div className="text-sm font-bold text-gray-800 text-center">{teamA}</div>
        </div>

        <div className="px-4 flex flex-col items-center gap-2">
          <Zap className={`w-6 h-6 ${theme === 'orange' ? 'text-orange-500' : 'text-green-500'}`} />
          <div className="text-sm font-bold text-gray-400">VS</div>
        </div>

        <div className="flex flex-col items-center gap-2 flex-1">
          <div className="text-4xl">{flagB}</div>
          <div className="text-sm font-bold text-gray-800 text-center">{teamB}</div>
        </div>
      </div>

      {/* Prediction Buttons or Started Message */}
      {hasStarted ? (
        <div className={`${themeBg} bg-opacity-10 border-2 ${themeBorder} rounded-lg py-3 text-center`}>
          <span className="text-sm font-bold text-gray-700">مسابقه شروع شده است</span>
        </div>
      ) : (
        <div className="grid grid-cols-3 gap-2">
          <button
            onClick={() => handleVote('A')}
            disabled={isLoading}
            className={`py-3 rounded-lg transition-all text-sm font-medium relative ${
              prediction === 'A'
                ? `${themeGradient} text-white shadow-lg`
                : `bg-white border-2 border-gray-200 hover:border-gray-300 text-gray-700 shadow-sm hover:shadow-md`
            }`}
          >
            {isLoading ? (
              <Loader2 className="w-4 h-4 animate-spin mx-auto" />
            ) : (
              `برد ${teamA.split(' ')[0]}`
            )}
          </button>
          <button
            onClick={() => handleVote('draw')}
            disabled={isLoading}
            className={`py-3 rounded-lg transition-all text-sm font-medium relative ${
              prediction === 'draw'
                ? `${themeGradient} text-white shadow-lg`
                : `bg-white border-2 border-gray-200 hover:border-gray-300 text-gray-700 shadow-sm hover:shadow-md`
            }`}
          >
            {isLoading ? (
              <Loader2 className="w-4 h-4 animate-spin mx-auto" />
            ) : (
              'مساوی'
            )}
          </button>
          <button
            onClick={() => handleVote('B')}
            disabled={isLoading}
            className={`py-3 rounded-lg transition-all text-sm font-medium relative ${
              prediction === 'B'
                ? `${themeGradient} text-white shadow-lg`
                : `bg-white border-2 border-gray-200 hover:border-gray-300 text-gray-700 shadow-sm hover:shadow-md`
            }`}
          >
            {isLoading ? (
              <Loader2 className="w-4 h-4 animate-spin mx-auto" />
            ) : (
              `برد ${teamB.split(' ')[0]}`
            )}
          </button>
        </div>
      )}
    </div>
  );
}

// components/matches/MatchCard.vue
<script setup lang="ts">
import type { AppTheme, PredictionChoice } from '~/types'
import { Clock, Trophy, Zap, Loader2, CheckCircle2 } from 'lucide-vue-next'

const props = withDefaults(
  defineProps<{
    theme: AppTheme
    teamA: string
    teamB: string
    flagA: string
    flagB: string
    date: string
    time: string
    reward: number
    prediction?: PredictionChoice
    hasStarted?: boolean
  }>(),
  { hasStarted: false },
)

const emit = defineEmits<{
  predict: [choice: PredictionChoice]
}>()

const isLoading = ref(false)
const showSuccess = ref(false)

const themeClasses = computed(() => useThemeClasses(props.theme))

const voteOptions = computed(() => [
  { key: 'A' as const, label: `برد ${teamShortName(props.teamA)}` },
  { key: 'draw' as const, label: 'مساوی' },
  { key: 'B' as const, label: `برد ${teamShortName(props.teamB)}` },
])

const itemClasses = computed(() => [
  props.hasStarted
    ? 'opacity-55 border-r-transparent'
    : props.prediction
      ? `${themeClasses.value.borderRight} bg-surface-hover/80`
      : 'border-r-transparent',
])

async function handleVote(vote: PredictionChoice) {
  if (props.hasStarted || isLoading.value) return

  isLoading.value = true
  await new Promise(resolve => setTimeout(resolve, 800))
  emit('predict', vote)
  isLoading.value = false
  showSuccess.value = true
  setTimeout(() => { showSuccess.value = false }, 3000)
}

function teamShortName(name: string) {
  return name.split(' ')[0]
}
</script>

<template>
  <div
    class="match-item relative px-4 py-3 transition-colors hover:bg-surface-hover/60"
    :class="itemClasses"
  >
    <!-- Card layout — عرض کم -->
    <div class="match-card-layout space-y-4">
      <div class="flex items-center justify-between gap-2" :class="{ 'blur-[0.5px]': hasStarted }">
        <div class="flex items-center gap-2 text-xs text-fg-muted min-w-0">
          <Clock class="w-4 h-4 flex-shrink-0" />
          <span class="truncate">{{ date }} • {{ time }}</span>
        </div>
        <div
          class="px-3 py-1.5 rounded-full text-xs font-bold flex items-center gap-1.5 shadow-sm flex-shrink-0"
          :class="themeClasses.lightBg"
        >
          <Trophy class="w-3.5 h-3.5" />
          <span>{{ formatFaNumber(reward) }} تومان</span>
        </div>
      </div>

      <div class="flex items-center justify-between gap-2" :class="{ 'blur-[0.5px]': hasStarted }">
        <div class="flex flex-col items-center gap-2 flex-1 min-w-0">
          <div class="text-2xl leading-none">{{ flagA }}</div>
          <div class="text-sm font-bold text-fg text-center truncate w-full px-1">{{ teamA }}</div>
        </div>

        <div class="px-2 sm:px-4 flex flex-col items-center gap-1 flex-shrink-0">
          <Zap class="w-3 h-3" :class="themeClasses.accent" />
          <div class="text-xs font-bold text-fg-faint">VS</div>
        </div>

        <div class="flex flex-col items-center gap-2 flex-1 min-w-0">
          <div class="text-2xl leading-none">{{ flagB }}</div>
          <div class="text-sm font-bold text-fg text-center truncate w-full px-1">{{ teamB }}</div>
        </div>
      </div>

      <div
        v-if="hasStarted"
        class="border-2 rounded-lg py-2.5 text-center"
        :class="[themeClasses.border, `${themeClasses.bg}/10`]"
      >
        <span class="text-sm font-bold text-fg-secondary">مسابقه شروع شده است</span>
      </div>

      <div v-else class="grid grid-cols-3 gap-2">
        <button
          v-for="option in voteOptions"
          :key="option.key"
          type="button"
          :disabled="isLoading"
          class="py-2.5 rounded-lg transition-all text-xs sm:text-sm font-medium"
          :class="
            prediction === option.key
              ? `${themeClasses.gradient} text-white shadow-lg`
              : 'bg-surface-inset border-2 border-line hover:border-line-strong text-fg-secondary shadow-sm hover:bg-surface-hover'
          "
          @click="handleVote(option.key)"
        >
          <Loader2 v-if="isLoading" class="w-4 h-4 animate-spin mx-auto" />
          <span v-else class="truncate block px-0.5">{{ option.label }}</span>
        </button>
      </div>
    </div>

    <!-- Row layout — عرض کافی -->
    <div class="match-row-layout">
      <div
        class="flex flex-col items-start justify-center w-[72px] flex-shrink-0 gap-0.5"
        :class="{ 'blur-[0.5px]': hasStarted }"
      >
        <span class="text-sm font-bold tabular-nums text-fg leading-none">{{ time }}</span>
        <span class="text-[10px] text-fg-muted leading-tight">{{ date }}</span>
      </div>

      <div
        class="flex-1 flex items-center justify-center gap-4 min-w-0 py-1"
        :class="{ 'blur-[0.5px]': hasStarted }"
      >
        <div class="flex flex-col items-center gap-1.5 flex-1 min-w-0">
          <span class="text-2xl leading-none">{{ flagA }}</span>
          <span class="text-sm font-semibold text-fg text-center truncate w-full px-1">{{ teamA }}</span>
        </div>

        <div class="flex flex-col items-center justify-center flex-shrink-0 self-stretch py-2">
          <span class="text-[10px] font-bold tracking-widest text-fg-faint">VS</span>
        </div>

        <div class="flex flex-col items-center gap-1.5 flex-1 min-w-0">
          <span class="text-2xl leading-none">{{ flagB }}</span>
          <span class="text-sm font-semibold text-fg text-center truncate w-full px-1">{{ teamB }}</span>
        </div>
      </div>

      <div
        class="flex items-center gap-1 px-2.5 py-1 rounded-lg text-[11px] font-bold flex-shrink-0"
        :class="[themeClasses.lightBg, themeClasses.accentDark, { 'blur-[0.5px]': hasStarted }]"
      >
        <Trophy class="w-3 h-3" />
        <span class="whitespace-nowrap">{{ formatFaNumber(reward) }} تومان</span>
      </div>

      <div class="w-[220px] flex-shrink-0">
        <div
          v-if="hasStarted"
          class="flex items-center justify-center gap-1.5 py-2.5 rounded-lg bg-surface-inset text-fg-muted"
        >
          <Clock class="w-3.5 h-3.5" />
          <span class="text-xs font-medium whitespace-nowrap">مسابقه شروع شده</span>
        </div>

        <div v-else class="grid grid-cols-3 gap-1.5">
          <button
            v-for="option in voteOptions"
            :key="option.key"
            type="button"
            :disabled="isLoading"
            class="py-2 px-1 rounded-md transition-all text-[11px] font-medium truncate"
            :class="
              prediction === option.key
                ? `${themeClasses.gradient} text-white shadow-sm`
                : 'bg-surface-inset border border-line hover:border-line-strong text-fg-secondary hover:bg-surface-hover'
            "
            @click="handleVote(option.key)"
          >
            <Loader2 v-if="isLoading" class="w-3.5 h-3.5 animate-spin mx-auto" />
            <span v-else>{{ option.label }}</span>
          </button>
        </div>
      </div>
    </div>
  </div>

  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="opacity-0 translate-y-2"
      enter-to-class="opacity-100 translate-y-0"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="opacity-100 translate-y-0"
      leave-to-class="opacity-0 translate-y-2"
    >
      <div
        v-if="showSuccess"
        class="fixed bottom-4 right-4 z-[100] bg-emerald-600 text-white px-4 py-2.5 rounded-lg shadow-lg shadow-emerald-900/40 flex items-center gap-2"
      >
        <CheckCircle2 class="w-4 h-4 flex-shrink-0" />
        <span class="text-sm font-medium">رای شما ثبت شد</span>
      </div>
    </Transition>
  </Teleport>
</template>
